### ISSUE TITLE
Eliminar la función save_convert_pdf_to_txt(self)

### ISSUE THREAD

**Issue by cibervicho** [frantizek/github-profile-achievements#12]
TODO : Eliminar la función.

Aunque luego pienso en esa frase que dice: 

Si ya funciona, ya ni le muevas.

_Originally posted by @frantizek in https://github.com/frantizek/CSF_xtractor/pull/9#discussion_r1322332692_

**Comment by frantizek** [comment]
Se elimino la funcion en este commit: https://github.com/frantizek/CSF_xtractor/pull/9/commits/8165579538a2859099c71e98aafb7c1339de7448
